export default {
    blocks: {
        rawstone: "create:asurine create:cut_asurine create:layered_asurine create:asurine_pillar create:cut_asurine_stairs create:cut_asurine_slab create:cut_asurine_wall create:cut_asurine_bricks create:cut_asurine_brick_stairs create:cut_asurine_brick_slab create:cut_asurine_brick_wall create:small_asurine_bricks create:small_asurine_brick_stairs create:small_asurine_brick_slab create:small_asurine_brick_wall create:crushing_wheel create:millstone create:shaft",
        rawgranite: "create:cut_granite create:layered_granite create:granite_pillar create:cut_granite_stairs create:cut_granite_slab create:cut_granite_wall create:cut_granite_bricks create:cut_granite_brick_stairs create:cut_granite_brick_slab create:cut_granite_brick_wall create:small_granite_bricks create:small_granite_brick_stairs create:small_granite_brick_slab create:small_granite_brick_wall create:crimsite create:cut_crimsite create:layered_crimsite create:crimsite_pillar create:cut_crimsite_stairs create:cut_crimsite_slab create:cut_crimsite_wall create:cut_crimsite_bricks create:cut_crimsite_brick_stairs create:cut_crimsite_brick_slab create:cut_crimsite_brick_wall create:small_crimsite_bricks create:small_crimsite_brick_stairs create:small_crimsite_brick_slab create:small_crimsite_brick_wall create:ochrum create:cut_ochrum create:layered_ochrum create:ochrum_pillar create:cut_ochrum_stairs create:cut_ochrum_slab create:cut_ochrum_wall create:cut_ochrum_bricks create:cut_ochrum_brick_stairs create:cut_ochrum_brick_slab create:cut_ochrum_brick_wall create:small_ochrum_bricks create:small_ochrum_brick_stairs create:small_ochrum_brick_slab create:small_ochrum_brick_wall",
        rawdiorite: "create:cut_diorite create:layered_diorite create:diorite_pillar create:cut_diorite_stairs create:cut_diorite_slab create:cut_diorite_wall create:cut_diorite_bricks create:cut_diorite_brick_stairs create:cut_diorite_brick_slab create:cut_diorite_brick_wall create:small_diorite_bricks create:small_diorite_brick_stairs create:small_diorite_brick_slab create:small_diorite_brick_wall",
        rawandesite: "create:cut_andesite create:layered_andesite create:andesite_pillar create:cut_andesite_stairs create:cut_andesite_slab create:cut_andesite_wall create:cut_andesite_bricks create:cut_andesite_brick_stairs create:cut_andesite_brick_slab create:cut_andesite_brick_wall create:small_andesite_bricks create:small_andesite_brick_stairs create:small_andesite_brick_slab create:small_andesite_brick_wall create:limestone create:cut_limestone create:layered_limestone create:limestone_pillar create:cut_limestone_stairs create:cut_limestone_slab create:cut_limestone_wall create:cut_limestone_bricks create:cut_limestone_brick_stairs create:cut_limestone_brick_slab create:cut_limestone_brick_wall create:small_limestone_bricks create:small_limestone_brick_stairs create:small_limestone_brick_slab create:small_limestone_brick_wall create:scoria create:cut_scoria create:layered_scoria create:scoria_pillar create:cut_scoria_stairs create:cut_scoria_slab create:cut_scoria_wall create:cut_scoria_bricks create:cut_scoria_brick_stairs create:cut_scoria_brick_slab create:cut_scoria_brick_wall create:small_scoria_bricks create:small_scoria_brick_stairs create:small_scoria_brick_slab create:small_scoria_brick_wall",
        rawdeepslate: "create:cut_deepslate create:layered_deepslate create:deepslate_pillar create:cut_deepslate_stairs create:cut_deepslate_slab create:cut_deepslate_wall create:cut_deepslate_bricks create:cut_deepslate_brick_stairs create:cut_deepslate_brick_slab create:cut_deepslate_brick_wall create:small_deepslate_bricks create:small_deepslate_brick_stairs create:small_deepslate_brick_slab create:small_deepslate_brick_wall create:scorchia create:cut_scorchia create:layered_scorchia create:scorchia_pillar create:cut_scorchia_stairs create:cut_scorchia_slab create:cut_scorchia_wall create:cut_scorchia_bricks create:cut_scorchia_brick_stairs create:cut_scorchia_brick_slab create:cut_scorchia_brick_wall create:small_scorchia_bricks create:small_scorchia_brick_stairs create:small_scorchia_brick_slab create:small_scorchia_brick_wall",
        rawcalcite: "create:cut_calcite create:layered_calcite create:calcite_pillar create:cut_calcite_stairs create:cut_calcite_slab create:cut_calcite_wall create:cut_calcite_bricks create:cut_calcite_brick_stairs create:cut_calcite_brick_slab create:cut_calcite_brick_wall create:small_calcite_bricks create:small_calcite_brick_stairs create:small_calcite_brick_slab create:small_calcite_brick_wall create:veridium create:cut_veridium create:layered_veridium create:veridium_pillar create:cut_veridium_stairs create:cut_veridium_slab create:cut_veridium_wall create:cut_veridium_bricks create:cut_veridium_brick_stairs create:cut_veridium_brick_slab create:cut_veridium_brick_wall create:small_veridium_bricks create:small_veridium_brick_stairs create:small_veridium_brick_slab create:small_veridium_brick_wall",
        smoothgranite: "create:polished_cut_granite create:polished_cut_granite_stairs create:polished_cut_granite_slab create:polished_cut_granite_wall create:polished_cut_dripstone create:polished_cut_dripstone_stairs create:polished_cut_dripstone_slab create:polished_cut_dripstone_wall create:polished_cut_crimsite create:polished_cut_crimsite_stairs create:polished_cut_crimsite_slab create:polished_cut_crimsite_wall create:polished_cut_ochrum create:polished_cut_ochrum_stairs create:polished_cut_ochrum_slab create:polished_cut_ochrum_wall",
        smoothdiorite: "create:polished_cut_calcite create:polished_cut_calcite_stairs create:polished_cut_calcite_slab create:polished_cut_calcite_wall",
        smoothandesite: "create:polished_cut_andesite create:polished_cut_andesite_stairs create:polished_cut_andesite_slab create:polished_cut_andesite_wall create:polished_cut_tuff create:polished_cut_tuff_stairs create:polished_cut_tuff_slab create:polished_cut_tuff_wall create:polished_cut_limestone create:polished_cut_limestone_stairs create:polished_cut_limestone_slab create:polished_cut_limestone_wall create:andesite_funnel create:andesite_tunnel create:andesite_door create:andesite_ladder create:andesite_scaffolding",
        smoothdeepslate: "create:polished_cut_deepslate create:polished_cut_deepslate_stairs create:polished_cut_deepslate_slab create:polished_cut_deepslate_wall create:polished_cut_scoria create:polished_cut_scoria_stairs create:polished_cut_scoria_slab create:polished_cut_scoria_wall create:polished_cut_scorchia create:polished_cut_scorchia_stairs create:polished_cut_scorchia_slab create:polished_cut_scorchia_wall",
        dripstone:"create:cut_dripstone create:layered_dripstone create:dripstone_pillar create:cut_dripstone_stairs create:cut_dripstone_slab create:cut_dripstone_wall create:cut_dripstone_bricks create:cut_dripstone_brick_stairs create:cut_dripstone_brick_slab create:cut_dripstone_brick_wall create:small_dripstone_bricks create:small_dripstone_brick_stairs create:small_dripstone_brick_slab create:small_dripstone_brick_wall",
        tuff:"create:tuff create:cut_tuff create:layered_tuff create:tuff_pillar create:cut_tuff_stairs create:cut_tuff_slab create:cut_tuff_wall create:cut_tuff_bricks create:cut_tuff_brick_stairs create:cut_tuff_brick_slab create:cut_tuff_brick_wall create:small_tuff_bricks create:small_tuff_brick_stairs create:small_tuff_brick_slab create:small_tuff_brick_wall",
        lapisblocks: "create:polished_cut_asurine create:polished_cut_asurine_stairs create:polished_cut_asurine_slab create:polished_cut_asurine_wall",
        prismarine: "create:polished_cut_veridium create:polished_cut_veridium_stairs create:polished_cut_veridium_slab create:polished_cut_veridium_wall",
        ironblock: "create:andesite_alloy_block create:industrial_iron_block create:brass_block create:zinc_block create:white_valve_handle create:orange_valve_handle create:magenta_valve_handle create:light_blue_valve_handle create:yellow_valve_handle create:lime_valve_handle create:pink_valve_handle create:gray_valve_handle create:light_gray_valve_handle create:cyan_valve_handle create:purple_valve_handle create:blue_valve_handle create:brown_valve_handle create:green_valve_handle create:red_valve_handle create:black_valve_handle create:copper_casing create:redstone_contact create:white_toolbox create:orange_toolbox create:magenta_toolbox create:light_blue_toolbox create:yellow_toolbox create:lime_toolbox create:pink_toolbox create:gray_toolbox create:light_gray_toolbox create:cyan_toolbox create:purple_toolbox create:blue_toolbox create:brown_toolbox create:green_toolbox create:red_toolbox create:black_toolbox",
        copperblock: "create:copper_shingles create:exposed_copper_shingles create:weathered_copper_shingles create:oxidized_copper_shingles create:waxed_copper_shingles create:waxed_exposed_copper_shingles create:waxed_weathered_copper_shingles create:waxed_oxidized_copper_shingles create:copper_shingle_stairs create:exposed_copper_shingle_stairs create:weathered_copper_shingle_stairs create:oxidized_copper_shingle_stairs create:waxed_copper_shingle_stairs create:waxed_exposed_copper_shingle_stairs create:waxed_weathered_copper_shingle_stairs create:waxed_oxidized_copper_shingle_stairs create:copper_shingle_slab create:exposed_copper_shingle_slab create:weathered_copper_shingle_slab create:oxidized_copper_shingle_slab create:waxed_copper_shingle_slab create:waxed_exposed_copper_shingle_slab create:waxed_weathered_copper_shingle_slab create:waxed_oxidized_copper_shingle_slab create:copper_tiles create:exposed_copper_tiles create:weathered_copper_tiles create:oxidized_copper_tiles create:waxed_copper_tiles create:waxed_exposed_copper_tiles create:waxed_weathered_copper_tiles create:waxed_oxidized_copper_tiles create:copper_tile_slab create:exposed_copper_tile_slab create:weathered_copper_tile_slab create:oxidized_copper_tile_slab create:waxed_copper_tile_slab create:waxed_exposed_copper_tile_slab create:waxed_weathered_copper_tile_slab create:waxed_oxidized_copper_tile_slab create:copper_tile_stairs create:exposed_copper_tile_stairs create:weathered_copper_tile_stairs create:oxidized_copper_tile_stairs create:waxed_copper_tile_stairs create:waxed_exposed_copper_tile_stairs create:waxed_weathered_copper_tile_stairs create:waxed_oxidized_copper_tile_stairs create:fluid_pipe create:mechanical_pump create:smart_fluid_pipe create:fluid_valve create:brass_casing create:elevator_pulley create:portable_fluid_interface create:spout create:steam_engine create:steam_whistle create:item_drain create:fluid_tank create:sequenced_gearshift create:flywheel create:rotation_speed_controller create:brass_funnel create:brass_tunnel create:display_link create:placard create:haunted_bell create:brass_door create:copper_door create:copper_ladder create:copper_scaffolding",
        goldblock: "create:train_door create:brass_ladder create:brass_scaffolding",
        bed: "create:white_seat create:orange_seat create:magenta_seat create:light_blue_seat create:yellow_seat create:lime_seat create:pink_seat create:gray_seat create:light_gray_seat create:cyan_seat create:purple_seat create:blue_seat create:brown_seat create:green_seat create:red_seat create:black_seat",
        noteblock:"create:cogwheel create:large_cogwheel create:water_wheel create:large_water_wheel create:andesite_casing create:gearbox create:clutch create:gearshift create:encased_chain_drive create:encased_fan create:adjustable_chain_gearshift create:rope_pulley create:stressometer create:speedometer create:linear_chassis create:secondary_linear_chassis create:radial_chassisc create:depot create:mechanical_press create:weighted_ejector",
        redstonecomponent:"create:pulse_extender create:powered_latch create:powered_toggle_latch create:pulse_repeater create:display_board",
        lever:"create:analog_lever",
        oakdoor:"create:oak_window",
        sprucedoor:"create:spruce_window",
        birchdoor:"create:birch_window",
        jungledoor:"create:jungle_window", 
        acaciadoor:"create:acacia_window",
        darkdoor:"create:dark_window",
        mangrovedoor:"create:mangrove_window",
        crimsondoor:"create:crimson_window",
        warpeddoor:"create:warped_window",
        cherrydoor:"create:cherry_window",
         
    },
    forms: { //form groups
        stoneraw: {
            base: true,
            prefix: ["cut","layered"],
            suffix: ["pillar"],
            infix: [["cut", "stairs"], ["cut", "slab"], ["cut", "wall"],
            ["cut", "bricks"], ["cut", "brick_stairs"], ["cut", "brick_slab"], ["cut", "brick_wall"],
            ["small", "bricks"], ["small", "brick_stairs"], ["small", "brick_slab"], ["small", "brick_wall"]]
        },
        stonepolished: {
            prefix: ["polished_cut"],
            infix: [["polished_cut", "stairs"],
            ["polished_cut", "slab"],
            ["polished_cut", "wall"]]
        },
        wood: {

        },
        coppers: {
            prefix: ["copper","exposed_copper","weathered_copper","oxidized_copper","waxed_copper","waxed_exposed_copper","waxed_weathered_copper","waxed_oxidized_copper"]
        }
    }
}