export default {
    forms: {
        woodlogs: {
            base:true,
            suffix:["log","wood"]
        },
        wood:{
            suffix:["planks", "slab", "stairs", "fence", "sign", "button", "pressure_plate"],
            infix:[["stripped", "log"], ["stripped", "wood"]]
        }
    },
    blocks: {
        dripleaf: "big_dripleaf_stem big_dripleaf small_dripleaf",
        wave: "grass fern",
        smallwave: "oak_sapling spruce_sapling birch_sapling jungle_sapling acacia_sapling dark_oak_sapling bamboo_sapling cherry_sapling dead_bush dandelion poppy blue_orchid allium azure_bluet red_tulip orange_tulip white_tulip pink_tulip oxeye_daisy cornflower lily_of_the_valley wither_rose sweet_berry_bush wheat carrots potatoes beetroots pumpkin_stem melon_stem nether_sprouts warped_roots crimson_roots torchflower_crop",
        tallgrasslow: "sunflower:half=lower lilac:half=lower rose_bush:half=lower peony:half=lower tall_grass:half=lower large_fern:half=lower",
        tallgrasshigh: "double_plant:half=upper sunflower:half=upper lilac:half=upper rose_bush:half=upper peony:half=upper tall_grass:half=upper large_fern:half=upper",
        verticalwave: "",
        hangingwave: "",
        treeleaves: "leaves leaves2 oak_leaves spruce_leaves birch_leaves jungle_leaves acacia_leaves dark_oak_leaves azalea_leaves flowering_azalea_leaves mangrove_leaves cherry_leaves",
        vines: "vine",
        reeds: "reeds attached_pumpkin_stem attached_melon_stem mangrove_propagule seagrass tall_seagrass kelp_plant kelp hanging_roots sugar_cane spore_blossom pink_petals pitcher_plant",
        brewingstand: "brewing_stand",
        hay: "hay_block",
        stonebrick: "stonebrick stone_slab:variant=stone_brick monster_egg:variant=stone_brick monster_egg:variant=mossy_brick monster_egg:variant=cracked_brick monster_egg:variant=chiseled_brick stone_bricks mossy_stone_bricks cracked_stone_bricks chiseled_stone_bricks stone_brick_stairs mossy_stone_brick_wall stone_brick_wall mossy_stone_brick_stairs mossy_stone_brick_slab infested_chiseled_stone_bricks infested_cracked_stone_bricks infested_mossy_stone_bricks infested_stone_bricks stone_brick_slab",
        anvil: "anvil chipped_anvil damaged_anvil",
        rail: "golden_rail powered_rail detector_rail rail activator_rail",
        cauldron: "cauldron hopper",
        watercauldron: "water_cauldron",
        snowcauldron: "powder_snow_cauldron",
        lavacauldron: "lava_cauldron",
        hopper: "hopper",
        lever: "lever",
        lectern: "lectern",
        lava: "lava flowing_lava",
        fire: "fire",
        soulfire: "soul_fire",
        rawstone: "stone stone_slab infested_stone stone_stairs stone_pressure_plate stone_button coal_ore smooth_stone smooth_stone_slab grindstone stonecutter",
        rawgranite: "stone:variant=granite granite granite_wall granite_stairs granite_slab",
        rawdiorite: "stone:variant=diorite diorite diorite_wall diorite_stairs diorite_slab",
        rawandesite: "stone:variant=andesite andesite andesite_wall andesite_stairs andesite_slab",
        rawdeepslate: "deepslate cobbled_deepslate infested_deepslate cobbled_deepslate_wall cobbled_deepslate_stairs cobbled_deepslate_slab deepslate_coal_ore",
        rawcalcite: "calcite",
        smoothstone: "",
        smoothgranite: "stone:variant=smooth_granite polished_granite polished_granite_stairs polished_granite_slab",
        smoothdiorite: "stone:variant=smooth_diorite polished_diorite polished_diorite_stairs polished_diorite_slab",
        smoothandesite: "stone:variant=smooth_andesite polished_andesite polished_andesite_stairs polished_andesite_slab packed_mud mud_bricks mud_brick_stairs mud_brick_slab mud_brick_wall bricks brick_slab brick_stairs brick_wall",
        smoothdeepslate: "polished_deepslate deepslate_bricks cracked_deepslate_bricks deepslate_tiles cracked_deepslate_tiles chiseled_deepslate polished_deepslate_wall deepslate_brick_wall deepslate_tile_wall polished_deepslate_stairs deepslate_brick_stairs deepslate_tile_stairs polished_deepslate_slab deepslate_brick_slab deepslate_tile_slab mud muddy_mangrove_roots mangrove_roots",
        dripstone: "dripstone_block pointed_dripstone daylight_detector",
        snowplant: "grass_block:snowy=true podzol:snowy=true mycelium:snowy=true",
        dirt: "dirt coarse_dirt rooted_dirt podzol:snowy=false mycelium:snowy=false dirt_path grass_path farmland:moisture=0 farmland:moisture=1 farmland:moisture=2 farmland:moisture=3 farmland:moisture=4 farmland:moisture=5 farmland:moisture=6",
        grass: "grass_block:snowy=false",
        wetsoil: "farmland:moisture=7",
        netherrack: "netherrack",
        bluenylium: "warped_nylium warped_wart_block",
        rednylium: "crimson_nylium nether_wart_block",
        cobblestone: "cobblestone stone_slab:variant=cobblestone stone_stairs monster_egg:variant=cobblestone cobblestone_wall cobblestone_slab mossy_cobblestone cobblestone_stairs infested_cobblestone cobblestone_wall mossy_cobblestone_wall mossy_cobblestone_stairs mossy_cobblestone_slab moss_block moss_carpet furnace:lit=false smoker:lit=false blast_furnace:lit=false lodestone piston sticky_piston piston_head dispenser dropper",
        oakwood: "log:variant=oak oak_log oak_wood",
        sprucewood: "log:variant=spruce spruce_log spruce_wood",
        birchwood: "log:variant=birch birch_log birch_wood",
        junglewood: "log:variant=jungle jungle_log jungle_wood",
        acaciawood: "log2:variant=acacia acacia_log acacia_wood",
        darkwood: "log2:variant=dark_oak dark_oak_log dark_oak_wood",
        mangrovewood: "mangrove_log mangrove_wood",
        crimsonwood: "crimson_stem crimson_hyphae",
        warpedwood: "warped_stem warped_hyphae",
        cherrywood: "cherry_log cherry_wood",
        oakplanks: "planks:variant=oak wooden_slab:variant=oak trapdoor fence fence_gate oak_planks stripped_oak_log stripped_oak_wood oak_slab petrified_oak_slab oak_fence oak_stairs oak_button oak_pressure_plate oak_trapdoor oak_fence_gate bookshelf crafting_table tripwire_hook",
        spruceplanks: "planks:variant=spruce wooden_slab:variant=spruce spruce_planks stripped_spruce_log stripped_spruce_wood spruce_slab spruce_fence spruce_stairs spruce_button spruce_pressure_plate spruce_trapdoor spruce_fence_gate",
        birchplanks: "planks:variant=birch wooden_slab:variant=birch birch_planks stripped_birch_log stripped_birch_wood birch_slab birch_fence birch_stairs birch_button birch_pressure_plate birch_trapdoor birch_fence_gate loom chiseled_bookshelf",
        jungleplanks: "planks:variant=jungle wooden_slab:variant=jungle jungle_planks stripped_jungle_log stripped_jungle_wood jungle_slab jungle_fence jungle_stairs jungle_button jungle_pressure_plate jungle_trapdoor jungle_fence_gate composter",
        acaciaplanks: "planks:variant=acacia wooden_slab:variant=acacia acacia_planks stripped_acacia_log stripped_acacia_wood acacia_slab acacia_fence acacia_stairs acacia_button acacia_pressure_plate acacia_trapdoor acacia_fence_gate",
        darkplanks: "planks:variant=dark_oak wooden_slab:variant=dark_oak dark_oak_planks stripped_dark_oak_log stripped_dark_oak_wood dark_oak_slab dark_oak_fence dark_oak_stairs dark_oak_button dark_oak_pressure_plate dark_oak_trapdoor dark_oak_fence_gate",
        mangroveplanks: "mangrove_planks stripped_mangrove_log stripped_mangrove_wood mangrove_slab mangrove_fence mangrove_stairs mangrove_button mangrove_pressure_plate mangrove_trapdoor mangrove_fence_gate",
        crimsonplanks: "crimson_planks stripped_crimson_stem stripped_crimson_hyphae crimson_slab crimson_fence crimson_stairs crimson_button crimson_pressure_plate crimson_trapdoor crimson_fence_gate",
        warpedplanks: "warped_planks stripped_warped_stem stripped_warped_hyphae warped_slab warped_fence warped_stairs warped_button warped_pressure_plate warped_trapdoor warped_fence_gate",
        cherryplanks: "cherry_planks cherry_stairs cherry_slab stripped_cherry_log stripped_cherry_wood cherry_fence cherry_fence_gate cherry_trapdoor cherry_pressure_plate cherry_button",
        bedrock: "bedrock",
        sand: "sand suspicious_sand",
        redsand: "red_sand",
        sandstone: "stone_slab:variant=sandstone sandstone chiseled_sandstone cut_sandstone sandstone_slab cut_sandstone_slab smooth_sandstone sandstone_stairs sandstone_wall smooth_sandstone_stairs smooth_sandstone_slab",
        redsandstone: "stone_slab2 red_sandstone red_sandstone_slab cut_red_sandstone_slab smooth_red_sandstone red_sandstone_wall chiseled_red_sandstone cut_red_sandstone red_sandstone_stairs smooth_red_sandstone_stairs smooth_red_sandstone_slab",
        netherite: "netherite_block",
        ancientdebris: "ancient_debris",
        ironbars: "iron_bars",
        irondoor: "iron_door",
        ironblock: "iron_block iron_trapdoor heavy_weighted_pressure_plate immersiveengineering:sheetmetal_iron ",
        ironraw: "raw_iron_block",
        ironore: "iron_ore",
        irondeepore: "deepslate_iron_ore",
        copperblock: "copper_block exposed_copper weathered_copper oxidized_copper cut_copper exposed_cut_copper weathered_cut_copper oxidized_cut_copper cut_copper_stairs exposed_cut_copper_stairs weathered_cut_copper_stairs oxidized_cut_copper_stairs cut_copper_slab exposed_cut_copper_slab weathered_cut_copper_slab oxidized_cut_copper_slab waxed_copper_block waxed_exposed_copper waxed_weathered_copper waxed_oxidized_copper waxed_cut_copper waxed_exposed_cut_copper waxed_weathered_cut_copper waxed_oxidized_cut_copper waxed_cut_copper_stairs waxed_exposed_cut_copper_stairs waxed_weathered_cut_copper_stairs waxed_oxidized_cut_copper_stairs waxed_cut_copper_slab waxed_exposed_cut_copper_slab waxed_weathered_cut_copper_slab waxed_oxidized_cut_copper_slab lightning_rod",
        copperraw: "raw_copper_block",
        copperore: "copper_ore",
        copperdeepore: "deepslate_copper_ore",
        goldblock: "gold_block light_weighted_pressure_plate",
        goldraw: "raw_gold_block",
        goldore: "gold_ore",
        golddeepore: "deepslate_gold_ore",
        goldnetherore: "nether_gold_ore",
        diamondblock: "diamond_block",
        diamondore: "diamond_ore",
        diamonddeepore: "deepslate_diamond_ore",
        amethystblock: "amethyst_block budding_amethyst",
        amethystbud: "small_amethyst_bud medium_amethyst_bud large_amethyst_bud amethyst_cluster",
        emeraldblock: "emerald_block",
        emeraldore: "emerald_ore",
        emeralddeepore: "deepslate_emerald_ore",
        azalea: "azalea flowering_azalea",
        lapisblock: "lapis_block",
        lapisore: "lapis_ore",
        lapisdeepore: "deepslate_lapis_ore",
        quartzblock: "stone_slab:variant=quartz quartz_block chiseled_quartz_block smooth_quartz quartz_slab quartz_bricks quartz_pillar quartz_stairs smooth_quartz_stairs smooth_quartz_slab",
        quartzore: "quartz_ore nether_quartz_ore",
        obsidian: "obsidian",
        purpur: "purpur_block purpur_pillar purpur_stairs purpur_slab",
        snow: "snow_layer snow_block snow powder_snow",
        packedice: "packed_ice",
        blueice: "blue_ice",
        pumpkin: "pumpkin carved_pumpkin",
        pumpkinlit: "lit_pumpkin jack_o_lantern",
        seapickle: "sea_pickle",
        soulsand: "soul_sand soul_soil",
        basalt: "basalt polished_basalt smooth_basalt",
        glowstone: "glowstone",
        netherbrick: "nether_brick stone_slab:variant=nether_brick nether_bricks nether_brick_slab cracked_nether_bricks chiseled_nether_bricks nether_brick_fence nether_brick_stairs nether_brick_wall",
        rednetherbrick: "red_nether_bricks red_nether_brick_slab red_nether_brick_stairs red_nether_brick_wall",
        melon: "melon_block melon",
        endstone: "end_stone end_bricks end_stone_bricks end_stone_brick_wall end_stone_brick_stairs end_stone_brick_slab",
        terracotta: "hardened_clay stained_hardened_clay terracotta white_terracotta orange_terracotta magenta_terracotta light_blue_terracotta yellow_terracotta lime_terracotta pink_terracotta gray_terracotta light_gray_terracotta cyan_terracotta purple_terracotta blue_terracotta brown_terracotta green_terracotta red_terracotta black_terracotta",
        terracottaglazed: "white_glazed_terracotta orange_glazed_terracotta magenta_glazed_terracotta light_blue_glazed_terracotta yellow_glazed_terracotta lime_glazed_terracotta pink_glazed_terracotta gray_glazed_terracotta light_gray_glazed_terracotta cyan_glazed_terracotta purple_glazed_terracotta blue_glazed_terracotta brown_glazed_terracotta green_glazed_terracotta red_glazed_terracotta black_glazed_terracotta",
        prismarine: "prismarine prismarine_slab prismarine_stairs prismarine_bricks prismarine_brick_slab prismarine_brick_stairs prismarine_wall",
        prismarinedark: "dark_prismarine dark_prismarine_stairs dark_prismarine_slab",
        sealantern: "sea_lantern",
        magma: "magma magma_block",
        command: "command_block chain_command_block repeating_command_block",
        concrete: "concrete white_concrete orange_concrete magenta_concrete light_blue_concrete yellow_concrete lime_concrete pink_concrete gray_concrete light_gray_concrete cyan_concrete purple_concrete blue_concrete brown_concrete green_concrete red_concrete black_concrete",
        concretepowder: "concrete_powder white_concrete_powder orange_concrete_powder magenta_concrete_powder light_blue_concrete_powder yellow_concrete_powder lime_concrete_powder pink_concrete_powder gray_concrete_powder light_gray_concrete_powder cyan_concrete_powder purple_concrete_powder blue_concrete_powder brown_concrete_powder green_concrete_powder red_concrete_powder black_concrete_powder",
        coralblock: "tube_coral_block brain_coral_block bubble_coral_block fire_coral_block horn_coral_block dead_tube_coral_block dead_brain_coral_block dead_bubble_coral_block dead_fire_coral_block dead_horn_coral_block",
        coral: "tube_coral brain_coral bubble_coral fire_coral horn_coral tube_coral_fan brain_coral_fan bubble_coral_fan fire_coral_fan horn_coral_fan dead_tube_coral dead_brain_coral dead_bubble_coral dead_fire_coral dead_horn_coral dead_tube_coral_fan dead_brain_coral_fan dead_bubble_coral_fan dead_fire_coral_fan dead_horn_coral_fan tube_coral_wall_fan brain_coral_wall_fan bubble_coral_wall_fan fire_coral_wall_fan horn_coral_wall_fan dead_tube_coral_wall_fan dead_brain_coral_wall_fan dead_bubble_coral_wall_fan dead_fire_coral_wall_fan dead_horn_coral_wall_fan",
        cryingobsidian: "crying_obsidian",
        blackstone: "blackstone blackstone_slab blackstone_stairs polished_blackstone polished_blackstone_slab polished_blackstone_stairs chiseled_polished_blackstone polished_blackstone_bricks polished_blackstone_brick_slab polished_blackstone_brick_stairs cracked_polished_blackstone_bricks polished_blackstone_pressure_plate polished_blackstone_button polished_blackstone_brick_wall polished_blackstone_wall blackstone_wall",
        gildedblackstone: "gilded_blackstone",
        waterlily: "waterlily lily_pad",
        torch: "torch wall_torch",
        endrod: "end_rod",
        chorusplant: "chorus_plant",
        chorusflower: "chorus_flower:age=0 chorus_flower:age=1 chorus_flower:age=2 chorus_flower:age=3 chorus_flower:age=4",
        chorusflowerfull: "chorus_flower:age=5",
        litfurnace: "lit_furnace furnace:lit=true",
        cactus: "cactus",
        noteblock: "noteblock note_block jukebox",
        soultorch: "soul_torch soul_wall_torch",
        mushroombrown: "brown_mushroom_block",
        mushroomred: "red_mushroom_block",
        mushroomstem: "mushroom_stem",
        glowlichen: "glow_lichen",
        enchantingtable: "enchanting_table",
        endportalempty: "end_portal_frame:eye=false",
        endportalsocketed: "end_portal_frame:eye=true",
        lantern: "lantern",
        soullantern: "soul_lantern",
        turtleegg: "turtle_egg sniffer_egg",
        dragonegg: "dragon_egg",
        litsmoker: "smoker:lit=true",
        litblastfurnace: "blast_furnace:lit=true",
        litcandle: "candle:lit=true white_candle:lit=true orange_candle:lit=true magenta_candle:lit=true light_blue_candle:lit=true yellow_candle:lit=true lime_candle:lit=true pink_candle:lit=true gray_candle:lit=true light_gray_candle:lit=true cyan_candle:lit=true purple_candle:lit=true blue_candle:lit=true brown_candle:lit=true green_candle:lit=true red_candle:lit=true black_candle:lit=true",
        respawnanchorempty: "respawn_anchor:charges=0",
        respawnanchor: "respawn_anchor:charges=1 respawn_anchor:charges=2 respawn_anchor:charges=3 respawn_anchor:charges=4",
        redstonewireon: "redstone_wire:power=1 redstone_wire:power=2 redstone_wire:power=3 redstone_wire:power=4 redstone_wire:power=5 redstone_wire:power=6 redstone_wire:power=7 redstone_wire:power=8 redstone_wire:power=9 redstone_wire:power=10 redstone_wire:power=11 redstone_wire:power=12 redstone_wire:power=13 redstone_wire:power=14 redstone_wire:power=15",
        redstonewireoff: "redstone_wire:power=0",
        redstonetorch: "redstone_torch redstone_wall_torch",
        redstoneblock: "redstone_block",
        redstoneoreoff: "redstone_ore:lit=false",
        redstoneoreon: "redstone_ore:lit=true",
        redstonedeeporeoff: "deepslate_redstone_ore:lit=false",
        redstonedeeporeon: "deepslate_redstone_ore:lit=true",
        cavevinesplant: "cave_vines_plant:berries=false cave_vines:berries=false",
        cavevinesplantfruit: "cave_vines_plant:berries=true cave_vines:berries=true",
        redstonelampoff: "redstone_lamp:lit=false",
        redstonelampon: "redstone_lamp:lit=true",
        redstonecomponent: "powered_repeater unpowered_repeater powered_comparator unpowered_comparator repeater comparator",
        shroomlight: "shroomlight",
        campfirelit: "campfire:lit=true",
        soulcampfirelit: "soul_campfire:lit=true",
        campfire: "campfire:lit=false soul_campfire:lit=false",
        observer: "observer",
        carpet: "carpet wool white_carpet orange_carpet magenta_carpet light_blue_carpet yellow_carpet lime_carpet pink_carpet gray_carpet light_gray_carpet cyan_carpet purple_carpet blue_carpet brown_carpet green_carpet red_carpet black_carpet white_wool orange_wool magenta_wool light_blue_wool yellow_wool lime_wool pink_wool gray_wool light_gray_wool cyan_wool purple_wool blue_wool brown_wool green_wool red_wool black_wool",
        boneblock: "bone_block",
        honeycomb: "barrel beehive bee_nest honeycomb_block",
        froglightochre: "ochre_froglight",
        froglightverdant: "verdant_froglight",
        froglightpearl: "pearlescent_froglight",
        reinforceddeepslate: "reinforced_deepslate",
        sculk: "sculk sculk_catalyst sculk_vein sculk_sensor:sculk_sensor_phase=inactive sculk_sensor:sculk_sensor_phase=cooldown",
        sculkshrieker: "sculk_shrieker",
        sculksensoron: "sculk_sensor:sculk_sensor_phase=active",
        sculksensoroncalibrated: "calibrated_sculk_sensor:sculk_sensor_phase=active",
        sculksensoroff: "calibrated_sculk_sensor:sculk_sensor_phase=inactive calibrated_sculk_sensor:sculk_sensor_phase=cooldown",
        spawner: "mob_spawner spawner",
        tuff: "tuff",
        clay: "clay",
        ladder: "ladder",
        gravel: "gravel suspicious_gravel",
        flowerpotmushroom: "flower_pot potted_red_mushroom potted_brown_mushroom potted_cactus potted_bamboo potted_flowering_azalea_bush potted_azalea_bush",
        flowerpot: "potted_dandelion potted_poppy potted_blue_orchid potted_allium potted_azure_bluet potted_red_tulip potted_orange_tulip potted_white_tulip potted_pink_tulip potted_oxeye_daisy potted_cornflower potted_lily_of_the_valley potted_wither_rose potted_oak_sapling potted_spruce_sapling potted_birch_sapling potted_jungle_sapling potted_acacia_sapling potted_dark_oak_sapling potted_mangrove_propagule potted_fern potted_dead_bush potted_crimson_roots potted_warped_roots pitcher_crop potted_cherry_sapling",
        structureblock: "structure_block jigsaw",
        chain: "chain",
        cobweb: "cobweb",
        driedkelpblock: "dried_kelp_block",
        bamboo: "bamboo",
        bambooblock: "bamboo_block stripped_bamboo_block bamboo_planks bamboo_mosaic bamboo_stairs bamboo_mosaic_stairs bamboo_slab bamboo_mosaic_slab bamboo_fence bamboo_fence_gate bamboo_trapdoor bamboo_pressure_plate bamboo_button scaffolding",
        torchflower: "torchflower",
        torchflowerpot: "potted_torchflower",
        twistingvines: "twisting_vines_plant twisting_vines weeping_vines weeping_vines_plant warped_fungus crimson_fungus",
        funguspot: "potted_crimson_fungus potted_warped_fungus",
        oakdoor: "wooden_door oak_door",
        sprucedoor: "spruce_door",
        birchdoor: "birch_door",
        jungledoor: "jungle_door",
        acaciadoor: "acacia_door",
        darkdoor: "dark_oak_door",
        mangrovedoor: "mangrove_door",
        crimsondoor: "crimson_door",
        warpeddoor: "warped_door",
        bamboodoor: "bamboo_door",
        cherrydoor: "cherry_door",
        stainedglass: "stained_glass white_stained_glass orange_stained_glass magenta_stained_glass light_blue_stained_glass yellow_stained_glass lime_stained_glass pink_stained_glass gray_stained_glass light_gray_stained_glass cyan_stained_glass purple_stained_glass blue_stained_glass brown_stained_glass green_stained_glass red_stained_glass black_stained_glass",
        stainedglasspane: "stained_glass_pane white_stained_glass_pane orange_stained_glass_pane magenta_stained_glass_pane light_blue_stained_glass_pane yellow_stained_glass_pane lime_stained_glass_pane pink_stained_glass_pane gray_stained_glass_pane light_gray_stained_glass_pane cyan_stained_glass_pane purple_stained_glass_pane blue_stained_glass_pane brown_stained_glass_pane green_stained_glass_pane red_stained_glass_pane black_stained_glass_pane",
        tintedglass: "tinted_glass",
        stainedglasspane: "stained_glass_pane white_stained_glass_pane orange_stained_glass_pane magenta_stained_glass_pane light_blue_stained_glass_pane yellow_stained_glass_pane lime_stained_glass_pane pink_stained_glass_pane gray_stained_glass_pane light_gray_stained_glass_pane cyan_stained_glass_pane purple_stained_glass_pane blue_stained_glass_pane brown_stained_glass_pane green_stained_glass_pane red_stained_glass_pane black_stained_glass_pane",
        tintedglass: "tinted_glass",
        slime: "slime slime_block",
        honey: "honey_block",
        portal: "portal nether_portal",
        endportal: "end_portal end_gateway",
        water: "water flowing_water",
        ice: "ice frosted_ice",
        glass: "glass",
        glasspane: "glass_pane",
        beacon: "beacon",
        sign: "oak_sign spruce_sign birch_sign jungle_sign acacia_sign dark_oak_sign oak_wall_sign spruce_wall_sign birch_wall_sign jungle_wall_sign acacia_wall_sign dark_oak_wall_sign crimson_sign crimson_wall_sign warped_sign warped_wall_sign mangrove_sign mangrove_wall_sign bamboo_sign bamboo_wall_sign oak_hanging_sign spruce_hanging_sign birch_hanging_sign jungle_hanging_sign acacia_hanging_sign dark_oak_hanging_sign oak_wall_hanging_sign spruce_wall_hanging_sign birch_wall_hanging_sign jungle_wall_hanging_sign acacia_wall_hanging_sign dark_oak_wall_hanging_sign crimson_hanging_sign crimson_wall_hanging_sign warped_hanging_sign warped_wall_hanging_sign mangrove_hanging_sign mangrove_wall_hanging_sign bamboo_hanging_sign bamboo_wall_hanging_sign cherry_sign cherry_wall_sign cherry_hanging_sign cherry_wall_hanging_sign",
        chest: "chest trapped_chest",
        endchest: "ender_chest",
        shulkerbox: "shulker_box white_shulker_box orange_shulker_box magenta_shulker_box light_blue_shulker_box yellow_shulker_box lime_shulker_box pink_shulker_box gray_shulker_box light_gray_shulker_box cyan_shulker_box purple_shulker_box blue_shulker_box brown_shulker_box green_shulker_box red_shulker_box black_shulker_box skeleton_skull wither_skeleton_skull player_head zombie_head creeper_head dragon_head white_banner orange_banner magenta_banner light_blue_banner yellow_banner lime_banner pink_banner gray_banner light_gray_banner cyan_banner purple_banner blue_banner brown_banner green_banner red_banner black_banner white_wall_banner orange_wall_banner magenta_wall_banner light_blue_wall_banner yellow_wall_banner lime_wall_banner pink_wall_banner gray_wall_banner light_gray_wall_banner cyan_wall_banner purple_wall_banner blue_wall_banner brown_wall_banner green_wall_banner red_wall_banner black_wall_banner white_bed orange_bed magenta_bed light_blue_bed yellow_bed lime_bed pink_bed gray_bed light_gray_bed cyan_bed purple_bed blue_bed brown_bed green_bed red_bed black_bed",
        conduit: "conduit",
        layertranslucent: "glass glass_pane beacon",
    }
}